# Reference from article "GitHub Actions share environment variables across workflows"
# by AJ BAJADA from JUNE 23, 2021
# source: https://arinco.com.au/blog/github-actions-share-environment-variables-across-workflows/

name: 'Set environment variables'
description: 'Configures environment variables for a workflow'
inputs:
  varFilePath:
    description: 'File path to variable file or directory. Defaults to ./.github/variables/* if none specified and runs against each file in that directory.'
    required: false
    default: ./.github/variables/*
runs:
  using: "composite"
  steps:
    - run: |
        sed "" ${{ inputs.varFilePath }} >> $GITHUB_ENV
      shell: bash
