name: Build Verification

on:
  workflow_call:
    secrets:
      UNITY_LICENSE:
        required: true

jobs:
  build-verification:
    name: Build Validation for Pull Request
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setvars
      - uses: ./.github/actions/git-lfs-cache
      - uses: ./.github/actions/unity-library-cache
        with:
          target_platform: WebGL

      - uses: game-ci/unity-builder@v2
        with:
          unityVersion: ${{ env.UNITY_VERSION }}
          buildMethod: ScriptBatch.TestBuild_WebGL
