name: Build Verification

on:
  pull_request:

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE_2021_1 }}

jobs:
  build-verification:
    name: Build Validation for Pull Request
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target_platform:
          - WebGL
          - Win64
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/git-lfs-cache
      - uses: ./.github/actions/unity-library-cache
        with:
          target_platform: ${{ matrix.target_platform }}

      - uses: game-ci/unity-builder@v2.0.4
        with:
          unityVersion: 2021.1.19f1
          buildMethod: ScriptBatch.TestBuild_${{ matrix.target_platform }}
