name: Create Package

on:
  release:
    types: [published]

jobs:
  create-package:
    runs-on: ubuntu-latest
    steps:
      - uses: nschloe/action-cached-lfs-checkout@v1

      - name: Setup Package
        run: sh ./setup-package.sh

      # install Node.js
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
          # Specifies the registry, this field is required!
          registry-url: https://registry.npmjs.org/
      
      - name: Publish Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Get tag name
        uses: olegtarasov/get-tag@v2.1.1
        id: tagName

      # Deploy build to release branch
      - name: Push package
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: release/${{ steps.tagName.outputs.tag }}
          force: true
