name: Create Package

on:
  release:
    types: [published]

jobs:
  create-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/git-lfs-cache

      - name: Setup Package
        run: sh ./setup-package.sh

      - name: Get tag name
        uses: olegtarasov/get-tag@v2.1.1
        id: tagName

      # Deploy build to release branch
      - name: Push git subdirectory as branch
        uses: s0/git-publish-subdir-action@v2.5.1
        with:
          REPO: self
          BRANCH: release/${{ steps.tagName.outputs.tag }}
          FOLDER: Packages/com.nickmaltbie.openkcc
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
