name: Create Package

on:
  release:
    types: [published]

jobs:
  create-package:
    runs-on: ubuntu-latest
    steps:
      - uses: nschloe/action-cached-lfs-checkout@v1

      - name: Setup Package
        run: sh ./setup-package.sh

      - name: Get tag name
        uses: olegtarasov/get-tag@v2.1.1
        id: tagName

      # Deploy build to release branch
      - name: Push package
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: release/${{ steps.tagName.outputs.tag }}
          force: true
