name: Create and Publish npm Package

on:
  push:
    tags:
      - '*'
  release:
    types: [published]

jobs:
  create-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/git-lfs-cache
      - uses: ./.github/actions/setvars

      - name: Setup Package
        run: sh ./setup-package.sh ${{ env.PACKAGE_PATH }}

      - name: Get tag name
        uses: olegtarasov/get-tag@v2.1.1
        id: releaseTagName

      # Deploy build to release branch
      - name: Push package via Release Tag
        if: "${{ steps.releaseTagName.outputs.tag != '' }}"
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: release/${{ steps.releaseTagName.outputs.tag }}
          force: true

      - name: Git lfs Pull
        run: git lfs pull
        shell: bash

      # Publish to 
      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      
      - name: Publish Package to NpmJS
        run: npm publish
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      # Restore back to original branch
      - uses: actions/checkout@v3
