on:
  push:
  release:
    types: [published]

jobs:
  create-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/git-lfs-cache

      - name: Setup Package
        run: setup-package.sh

      - name: Get tag name
        uses: olegtarasov/get-tag@v2.1.1
        id: tagName

      # Deploy build to release branch
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: release/${{ steps.tagName.outputs.tag }}
          force_orphan: true
          publish_dir: Builds/OpenKCC-WebGL
          github_token: ${{ secrets.GITHUB_TOKEN }}
