name: Create and Publish npm Package

on:
  workflow_call:
    inputs:
      version-name:
        required: false
        type: string
        default: ""
      release-publish:
        required: false
        type: boolean
        default: false
      latest-publish:
        required: false
        type: boolean
        default: true
    secrets:
      token:
        required: false
        type: string
        default: ""

jobs:
  create-openkcc-package:
    name: Create OpenKCC package ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: "main"
            branch_prefix: "release"
            package_path: "./Packages/com.nickmaltbie.openkcc"
            samples: "ExampleFirstPersonKCC,SimplifiedDemoKCC,ExampleColliderShapes"
          - name: "netcode"
            branch_prefix: "release/netcode"
            package_path: "./Packages/com.nickmaltbie.openkcc.netcode"
            samples: "NetcodeExample,MoleKCCSample"
          - name: "cinemachine"
            branch_prefix: "release/cinemachine"
            package_path: "./Packages/com.nickmaltbie.openkcc.cinemachine"
            samples: "CinemachineExample"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/git-lfs-cache
      - uses: ./.github/actions/setvars

      - name: Setup Package
        run: ./setup-package.sh -p ${{ matrix.package_path }} -s ${{ matrix.samples }}

      # Deploy build to release branch
      - name: Push package to git branch ${{ matrix.branch_prefix }}/${{ inputs.version-name }}
        if: ${{ inputs.release-publish }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.token }}
          branch: ${{ matrix.branch_prefix }}/${{ inputs.version-name }}
          force: true

      # Deploy build to release branch
      - name: Push package to git branch ${{ matrix.branch_prefix }}/latest
        if: ${{ inputs.latest-publish }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.token }}
          branch: ${{ matrix.branch_prefix }}/latest
          force: true

      - name: Git lfs Pull
        run: git lfs pull
        shell: bash

      # Publish to 
      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      
      - name: Publish Package to NpmJS
        if: "${{ inputs.release-publish }}"
        run: npm publish
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      # Restore back to original branch
      - uses: actions/checkout@v3
