name: Create Package

on:
  release:
    types: [published]

jobs:
  create-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/git-lfs-cache

      - name: Setup Package
        run: sh ./setup-package.sh

      - name: Get tag name
        uses: olegtarasov/get-tag@v2.1.1
        id: tagName

      # Deploy build to release branch
      - name: Push package
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: release/${{ steps.tagName.outputs.tag }}
          force: true

      # Publish to 
      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      
      - name: Publish Package to NpmJS
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
