name: Create and Publish npm Package

on:
  push:
    tags:
      - '*'

jobs:
  create-release-package:
    runs-on: ubuntu-latest
    steps:
      - name: Create Latest Release Package
        uses: ./.github/workflows/create-package.yml
        with:
          latest-publish: false
          release-publish: true
          version-name: ${{ github.ref }}
