name: Create and Publish npm Package

on:
  push:
    tags:
      - '*'

jobs:
  create-release-package:
    uses: ./.github/workflows/create-package.yml
    secrets:
      token: ${{ secrets.NPM_TOKEN }}
    with:
      latest-publish: false
      release-publish: true
      version-name: ${{ github.ref_name }}
