name: Pull Request Validation

on:
  pull_request:

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build-verification:
    runs-on: ubuntu-latest
    steps:
      - name: Verify build for project
        uses: ./.github/workflows/build-verification.yml
        with:
          UNITY_LICENSE: ${{ env.UNITY_LICENSE }}
      
      - name: Test Verification
        uses: ./github/workflows/test-validation.yml
        with:
          UNITY_LICENSE: ${{ env.UNITY_LICENSE }}
  
  project-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Project linting
        uses: ./.github/workflows/format.yml
        with:
          UNITY_LICENSE: ${{ env.UNITY_LICENSE }}
