name: Tests Validation

on:
  pull_request:
  push:
    branches:
      - 'main'

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  test-validation-pull-request:
    strategy:
      fail-fast: false
    name: Test Validation for Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setvars
      - uses: ./.github/actions/git-lfs-cache
      - uses: ./.github/actions/unity-library-cache
        with:
          target_platform: WebGL

      - name: Run All Tests for Unity ${{ env.UNITY_VERSION }}
        id: tests
        uses: game-ci/unity-test-runner@v2.0.2
        with:
          unityVersion: ${{ env.UNITY_VERSION }}
          testMode: All
          checkName: All Test Results
          customParameters: -testFilter "nickmaltbie.OpenKCC.Tests.*" -nographics
          coverageOptions: 'generateAdditionalMetrics;generateHtmlReport;generateBadgeReport;assemblyFilters:+nickmaltbie.OpenKCC*;pathFilters:+**/Packages/**,-**/Tests/**'

      - name: Copy Coverage Results
        run: |
          mkdir -p allResults
          sudo cp -r ${{ steps.tests.outputs.coveragePath }} allResults/CodeCoverage
          sudo cp -r ${{ steps.tests.outputs.artifactsPath }} allResults/artifacts
